spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/**
        - id: admin-service
          uri: lb://admin
          predicates:
            - Path=/api/v1/admin/**
        - id: client-service
          uri: lb://client
          predicates:
            - Path=/api/v1/client/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false

server:
  port: 8080
  servlet:
    context-path: /api/v1/api-gateway

# Management endpoints configuration (Production-ready)
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    gateway:
      access: read-only
  health:
    diskspace:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG
    '[org.springframework.cloud.loadbalancer]': DEBUG