apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: spring-microservice
  labels:
    app: admin-service
    service: admin
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
        service: admin
        version: "1.0"
    spec:
      containers:
        - name: admin-service
          image: public.ecr.aws/k2g9v6r8/spring-microservice/shop-admin:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://service-registry.spring-microservice.svc.cluster.local:8761/eureka/"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /admin/actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /admin/actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10