apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: spring-microservice
  labels:
    app: auth-service
    service: auth
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        service: auth
        version: "1.0"
    spec:
      containers:
        - name: auth-service
          image: public.ecr.aws/k2g9v6r8/spring-microservice/shop-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://service-registry.spring-microservice.svc.cluster.local:8761/eureka/"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/auth/actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/auth/actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10