apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: spring-microservice
  labels:
    app: admin-service
    service: admin
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app: admin-service