apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: spring-microservice
  labels:
    app: auth-service
    service: auth
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: auth-service