apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: spring-microservice
  labels:
    app: client-service
    service: client
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
  selector:
    app: client-service